[version]
  path = 'fuz/__init__.py'

[build.hooks.vcs]
  version-file = "_version.py"

[metadata]
  allow-direct-references = true

  [metadata.hooks.vcs.urls]
    # https://packaging.python.org/en/latest/specifications/well-known-project-urls/#well-known-labels
    changelog = 'https://github.com/viamiraia/fuz/blob/master/changelog.md'
    documentation = 'https://fuz.raia.fun'
    homepage = 'https://fuz.raia.fun'
    issues = 'https://github.com/viamiraia/fuz/issues'
    source = 'https://github.com/viamiraia/fuz'
    source_archive = "https://github.com/viamiraia/fuz/archive/{commit_hash}.zip"

[metadata.hooks.fancy-pypi-readme]
  content-type = "text/markdown"

  [[metadata.hooks.fancy-pypi-readme.fragments]]
    end-before = "\n<!-- end-short -->"
    path = "readme.md"
    start-after = "<!-- begin-short -->\n"
